arch:
  ref0:
    decoder:
      out_features: 1
      layers: 1
      layer_size: 32

    fno:
      in_channels: 1
      dimension: 2
      latent_channels: 32
      fno_layers: 4
      fno_modes: 12
      padding: 9

  ref1:
    decoder:
      out_features: 1
      layers: 1
      layer_size: 32

    fno:
      in_channels: 2
      dimension: 2
      latent_channels: 32
      fno_layers: 4
      fno_modes: 12
      padding: 9

normaliser:
  permeability:
    mean: 1.25
    std: .75
  darcy:
    mean: 6.145E-5
    std: 3.49E-5

scheduler:
  initial_lr: 1.E-3
  decay_rate: .95
  decay_epochs: 10

training:
  batch_size: 64
  rec_results_freq : 20
  max_epochs: 60
  training_set: './data/training_data.npy'

validation:
  batch_size: 64
  validation_epochs: 10
  validation_set: './data/validation_data.npy'

inference:
  batch_size: 64
  inference_set: './data/out_of_sample.npy'
