# Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

sfno_73ch_cos_zenith: &SFNO_73CH_COS_ZENITH

    N_grid_channels: 0
    N_in_channels: 74
    N_out_channels: 73
    N_target_channels: 73
    activation_function: gelu
    add_grid: false
    add_landmask: false
    add_noise: false
    add_orography: false
    add_zenith: true
    amp_mode: none
    batch_size: 1
    channel_names:
    - u10m
    - v10m
    - u100m
    - v100m
    - t2m
    - sp
    - msl
    - tcwv
    - u50
    - u100
    - u150
    - u200
    - u250
    - u300
    - u400
    - u500
    - u600
    - u700
    - u850
    - u925
    - u1000
    - v50
    - v100
    - v150
    - v200
    - v250
    - v300
    - v400
    - v500
    - v600
    - v700
    - v850
    - v925
    - v1000
    - z50
    - z100
    - z150
    - z200
    - z250
    - z300
    - z400
    - z500
    - z600
    - z700
    - z850
    - z925
    - z1000
    - t50
    - t100
    - t150
    - t200
    - t250
    - t300
    - t400
    - t500
    - t600
    - t700
    - t850
    - t925
    - t1000
    - r50
    - r100
    - r150
    - r200
    - r250
    - r300
    - r400
    - r500
    - r600
    - r700
    - r850
    - r925
    - r1000
    checkpointing: false
    complex_activation: real
    crop_size_x: null
    crop_size_y: null
    cuda_graph_mode: none
    data_num_shards: 64
    data_shard_id: 0
    disable_ddp: false
    dt: 1
    embed_dim: 384
    enable_benchy: false
    enable_nhwc: false
    enable_synthetic_data: false
    epsilon_factor: 0
    exp_dir: './runs'
    filter_type: linear
    finetune: false
    global_batch_size: 64
    global_means_path: /stats/global_means.npy
    global_stds_path: /stats/global_stds.npy
    gridtype: sinusoidal
    h_parallel_size: 1
    hard_thresholding_fraction: 1.0
    ics_type: specify_number
    ifs_acc_path: /ifs
    img_crop_offset_x: 0
    img_crop_offset_y: 0
    img_crop_shape_x: 721
    img_crop_shape_y: 1440
    img_local_offset_x: 0
    img_local_offset_y: 0
    img_local_shape_x: 721
    img_local_shape_y: 1440
    img_shape_x: 721
    img_shape_y: 1440
    in_channels:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
    - 32
    - 33
    - 34
    - 35
    - 36
    - 37
    - 38
    - 39
    - 40
    - 41
    - 42
    - 43
    - 44
    - 45
    - 46
    - 47
    - 48
    - 49
    - 50
    - 51
    - 52
    - 53
    - 54
    - 55
    - 56
    - 57
    - 58
    - 59
    - 60
    - 61
    - 62
    - 63
    - 64
    - 65
    - 66
    - 67
    - 68
    - 69
    - 70
    - 71
    - 72
    inf_data_path: /data/out_of_sample
    io_grid:
    - 1
    - 1
    - 1
    io_rank:
    - 0
    - 0
    - 0
    jit_mode: none
    landmask_path: /invariants/e5.oper.invariant.128_172_lsm.ll025sc.1979010100_1979010100.nc
    log_to_screen: true
    log_to_wandb: true
    log_video: 0
    loss: geometric l2
    lr: 0.001
    lr_warmup_steps: 0
    masked_acc: false
    maskpath: null
    matmul_parallel_size: 1
    max_epochs: 60
    max_path: /stats/maxs.npy
    min_path: /stats/mins.npy
    mlp_mode: serial
    model_parallel_names:
    - h
    - w
    - matmul
    model_parallel_size: 1
    model_parallel_sizes:
    - 1
    - 1
    - 1
    multigrid_mode: none
    multistep_count: 1
    n_eval_samples: 256
    n_future: 0
    n_history: 0
    n_initial_conditions: 5
    nettype: sfno
    noise_std: 0.0
    normalization: zscore
    normalization_layer: instance_norm
    num_blocks: 8
    num_data_workers: 4
    num_layers: 8
    num_visualization_workers: 2
    operator_type: dhconv
    optimizer_beta1: 0.9
    optimizer_beta2: 0.95
    optimizer_max_grad_norm: 32
    optimizer_type: FusedAdam
    orography_path: /invariants/e5.oper.invariant.128_129_z.ll025sc.1979010100_1979010100.nc
    out_channels:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
    - 32
    - 33
    - 34
    - 35
    - 36
    - 37
    - 38
    - 39
    - 40
    - 41
    - 42
    - 43
    - 44
    - 45
    - 46
    - 47
    - 48
    - 49
    - 50
    - 51
    - 52
    - 53
    - 54
    - 55
    - 56
    - 57
    - 58
    - 59
    - 60
    - 61
    - 62
    - 63
    - 64
    - 65
    - 66
    - 67
    - 68
    - 69
    - 70
    - 71
    - 72
    parameters_reduction_buffer_count: 1
    perturb: false
    prediction_length: 35
    prediction_type: iterative
    print_timings_frequency: 10
    resuming: true
    roll: false
    save_channel: false
    save_checkpoint: true
    save_raw_forecasts: true
    scale_factor: 6
    scheduler: CosineAnnealingLR
    scheduler_T_max: 60
    separable: false
    spectral_transform: sht
    split_data_channels: false
    target: default
    time_means_path: /stats/time_means.npy
    train_data_path: /train
    use_mlp: true
    valid_autoreg_steps: 20
    valid_data_path: /test
    verbose: false
    w_parallel_size: 1
    weight_decay: 0.0
    wind_channels:
    - 0
    - 1
    - 2
    - 3
    - 8
    - 21
    - 9
    - 22
    - 10
    - 23
    - 11
    - 24
    - 12
    - 25
    - 13
    - 26
    - 14
    - 27
    - 15
    - 28
    - 16
    - 29
    - 17
    - 30
    - 18
    - 31
    - 19
    - 32
    - 20
    - 33
    wandb_name: None # If None, config will be used but you can override it here
    wandb_group: None # If None, will be 'era5_wind' + config, but you can override it here
    wandb_project: "Modulus-Launch"
    wandb_entity: "Modulus"
    wireup_info: mpi
    wireup_store: tcp
    world_size: 64
