defaults :
  - modulus_default
  - /arch/conv_fully_connected_cfg@arch.decoder
  - /arch/fno_cfg@arch.fno
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

jit: false

arch:
  decoder:
    input_keys: [z, 32]
    output_keys: sol
    nr_layers: 1
    layer_size: 32
  fno:
    dimension: 3
    nr_fno_layers: 4
    fno_modes: 12
    padding: 9
        # large LR    
scheduler:
  decay_rate: 0.95
  decay_steps: 1000

training:
  rec_results_freq : 500
  max_steps : 25000

batch_size:
  grid: 4
  validation: 1
    #run_mode: 'eval'


